- name: Create user
  import_tasks: user.yaml
  tags:
    - user

- name: install dotfiles
  import_tasks: config.yaml
  tags:
    - dotfiles

- name: Install plugins
  import_tasks: plugins.yaml
  tags:
    - plugins

- name: Setup editor
  import_tasks: editor.yaml
  tags:
    - editor

- name: Setup user specific statup apps
  import_tasks: startup.yaml
  tags:
    - startup
