- name: Update cache and packages
  become: true
  become_user: root
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install pacman packages
  become: true
  become_user: root
  pacman:
    name: "{{ packages }}"
    state: present

- name: Enable NetworkManager
  systemd_service:
    name: NetowrkManager.service
    enabled: true
